# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1082/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1082/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Documents/cpp_projects/race_game/FKD-Racing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Documents/cpp_projects/race_game/FKD-Racing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1082/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1082/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/cpp_projects/race_game/FKD-Racing/CMakeFiles /home/alex/Documents/cpp_projects/race_game/FKD-Racing//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/cpp_projects/race_game/FKD-Racing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FKD_Racing

# Build rule for target.
FKD_Racing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FKD_Racing
.PHONY : FKD_Racing

# fast build rule for target.
FKD_Racing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/build
.PHONY : FKD_Racing/fast

source/Car.o: source/Car.cpp.o
.PHONY : source/Car.o

# target to build an object file
source/Car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Car.cpp.o
.PHONY : source/Car.cpp.o

source/Car.i: source/Car.cpp.i
.PHONY : source/Car.i

# target to preprocess a source file
source/Car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Car.cpp.i
.PHONY : source/Car.cpp.i

source/Car.s: source/Car.cpp.s
.PHONY : source/Car.s

# target to generate assembly for a file
source/Car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Car.cpp.s
.PHONY : source/Car.cpp.s

source/Draw.o: source/Draw.cpp.o
.PHONY : source/Draw.o

# target to build an object file
source/Draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Draw.cpp.o
.PHONY : source/Draw.cpp.o

source/Draw.i: source/Draw.cpp.i
.PHONY : source/Draw.i

# target to preprocess a source file
source/Draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Draw.cpp.i
.PHONY : source/Draw.cpp.i

source/Draw.s: source/Draw.cpp.s
.PHONY : source/Draw.s

# target to generate assembly for a file
source/Draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Draw.cpp.s
.PHONY : source/Draw.cpp.s

source/Enemy.o: source/Enemy.cpp.o
.PHONY : source/Enemy.o

# target to build an object file
source/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Enemy.cpp.o
.PHONY : source/Enemy.cpp.o

source/Enemy.i: source/Enemy.cpp.i
.PHONY : source/Enemy.i

# target to preprocess a source file
source/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Enemy.cpp.i
.PHONY : source/Enemy.cpp.i

source/Enemy.s: source/Enemy.cpp.s
.PHONY : source/Enemy.s

# target to generate assembly for a file
source/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Enemy.cpp.s
.PHONY : source/Enemy.cpp.s

source/EnemySystem.o: source/EnemySystem.cpp.o
.PHONY : source/EnemySystem.o

# target to build an object file
source/EnemySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/EnemySystem.cpp.o
.PHONY : source/EnemySystem.cpp.o

source/EnemySystem.i: source/EnemySystem.cpp.i
.PHONY : source/EnemySystem.i

# target to preprocess a source file
source/EnemySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/EnemySystem.cpp.i
.PHONY : source/EnemySystem.cpp.i

source/EnemySystem.s: source/EnemySystem.cpp.s
.PHONY : source/EnemySystem.s

# target to generate assembly for a file
source/EnemySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/EnemySystem.cpp.s
.PHONY : source/EnemySystem.cpp.s

source/Game.o: source/Game.cpp.o
.PHONY : source/Game.o

# target to build an object file
source/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Game.cpp.o
.PHONY : source/Game.cpp.o

source/Game.i: source/Game.cpp.i
.PHONY : source/Game.i

# target to preprocess a source file
source/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Game.cpp.i
.PHONY : source/Game.cpp.i

source/Game.s: source/Game.cpp.s
.PHONY : source/Game.s

# target to generate assembly for a file
source/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Game.cpp.s
.PHONY : source/Game.cpp.s

source/ScoreSystem.o: source/ScoreSystem.cpp.o
.PHONY : source/ScoreSystem.o

# target to build an object file
source/ScoreSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/ScoreSystem.cpp.o
.PHONY : source/ScoreSystem.cpp.o

source/ScoreSystem.i: source/ScoreSystem.cpp.i
.PHONY : source/ScoreSystem.i

# target to preprocess a source file
source/ScoreSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/ScoreSystem.cpp.i
.PHONY : source/ScoreSystem.cpp.i

source/ScoreSystem.s: source/ScoreSystem.cpp.s
.PHONY : source/ScoreSystem.s

# target to generate assembly for a file
source/ScoreSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/ScoreSystem.cpp.s
.PHONY : source/ScoreSystem.cpp.s

source/Update.o: source/Update.cpp.o
.PHONY : source/Update.o

# target to build an object file
source/Update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Update.cpp.o
.PHONY : source/Update.cpp.o

source/Update.i: source/Update.cpp.i
.PHONY : source/Update.i

# target to preprocess a source file
source/Update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Update.cpp.i
.PHONY : source/Update.cpp.i

source/Update.s: source/Update.cpp.s
.PHONY : source/Update.s

# target to generate assembly for a file
source/Update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/Update.cpp.s
.PHONY : source/Update.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FKD_Racing.dir/build.make CMakeFiles/FKD_Racing.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FKD_Racing"
	@echo "... source/Car.o"
	@echo "... source/Car.i"
	@echo "... source/Car.s"
	@echo "... source/Draw.o"
	@echo "... source/Draw.i"
	@echo "... source/Draw.s"
	@echo "... source/Enemy.o"
	@echo "... source/Enemy.i"
	@echo "... source/Enemy.s"
	@echo "... source/EnemySystem.o"
	@echo "... source/EnemySystem.i"
	@echo "... source/EnemySystem.s"
	@echo "... source/Game.o"
	@echo "... source/Game.i"
	@echo "... source/Game.s"
	@echo "... source/ScoreSystem.o"
	@echo "... source/ScoreSystem.i"
	@echo "... source/ScoreSystem.s"
	@echo "... source/Update.o"
	@echo "... source/Update.i"
	@echo "... source/Update.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

